version: "3"

networks:
  xs2a-net:

volumes:
  keycloak-data:
  aspsp-mock-mongo-config:
  aspsp-mock-mongo-data:
  consent-management-data:

services:
# ASPSP-IDP
  xs2a-idp:
    build:
      context: aspsp-idp
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      - JAVA_TOOL_OPTIONS="-Xmx512M"
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin123
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
      - POSTGRES_PORT_5432_TCP_ADDR=keycloak-postgres
    depends_on:
      - keycloak-postgres
    ports:
      - "8081:8080"
    networks:
      - xs2a-net

  keycloak-postgres:
    image: centos/postgresql-95-centos7
    volumes:
      - keycloak-data:/var/lib/pgsql/data
    restart: on-failure
    networks:
      - xs2a-net
    environment:
      - POSTGRESQL_ADMIN_PASSWORD=postgres
      - POSTGRESQL_DATABASE=keycloak
      - POSTGRESQL_USER=keycloak
      - POSTGRESQL_PASSWORD=keycloak
    expose:
      - 5432

  aspsp-mock-mongo:
    image: mongo
    restart: on-failure
    ports:
      - "27017:27017"
    networks:
      - xs2a-net
    volumes:
      - aspsp-mock-mongo-config:/data/configdb
      - aspsp-mock-mongo-data:/data/db

  consent-management-postgres:
     image: centos/postgresql-95-centos7
     volumes:
       - consent-management-data:/var/lib/pgsql/data
     restart: on-failure
     networks:
       - xs2a-net
     environment:
       - POSTGRESQL_ADMIN_PASSWORD=postgres
       - POSTGRESQL_DATABASE=consent
       - POSTGRESQL_USER=cms
       - POSTGRESQL_PASSWORD=cms
     ports:
       - 5432:5432
